name: Build and Publish to npm

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Publish to npm
        run: npm publish
        if: ${{ matrix.node-version == '20.x' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
